Make sure we are able to generate the git documentation properly
Needs brew install asciidoc xmlto docbook  to work.

Signed-off-by: Pedro Melo <melo@simplicidade.org>

diff --git a/bin/x-git-update-to-latest-version b/bin/x-git-update-to-latest-version
--- a/bin/x-git-update-to-latest-version
+++ b/bin/x-git-update-to-latest-version
@@ -71,6 +71,9 @@ echo
 PERL_PATH="/usr/bin/env perl"
 export PERL_PATH
 
+XML_CATALOG_FILES=`brew --prefix`"/etc/xml/catalog"
+export XML_CATALOG_FILES
+
 make configure
 ./configure --prefix=$BASE/git-$version
 make -j6 all
@@ -79,11 +82,17 @@ if [ $? != 0 ] ; then
   exit 1
 fi
 
+make doc
+if [ $? != 0 ] ; then
+  echo "******* Documentation generation failed! "
+  exit 1
+fi
+
 if [ "$run_tests" == "yes" ] ; then
   echo
-  echo "******* Installing git and documentation"
+  echo "******* Running test suite"
   echo
-  
+
   make test
 fi
 
@@ -91,8 +100,7 @@ echo
 echo "******* Installing git and documentation"
 echo
 
-sudo make install
-sudo make quick-install-man quick-install-html
+sudo make install install-doc install-man install-html
 
 
 echo
